#!/bin/sh -f

bush_home=../../bush

. ${bush_home}/args

build_args="${build_args} -app_use_SOPHYA"
#build_args="${build_args} -app_use_sophya_dev"
#build_args="${build_args} -app_use_Python"

. ${bush_home}/app_header_use

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
if [ "${use_sophya_dev}" = yes ] ; then
  cppflags="${cppflags} -DAPP_USE_SOPHYA"
fi

cppfiles="${cppfiles} ${inlib_home}/inlib/yacc/cexpr_lexer.cpp"
cppfiles="${cppfiles} ${inlib_home}/inlib/yacc/cexpr_eval.cpp"

if [ ${build_x11} = yes ] ; then
  cppflags="${cppflags} -DEXLIB_APP_HAS_TERM -DEXLIB_APP_TERM_INSH"
  use_Getline=yes
fi
if [ ${build_sdk_mac} = yes ] ; then
  cppflags="${cppflags} -DEXLIB_APP_HAS_TERM -DEXLIB_APP_TERM_INSH"
  use_Getline=yes
fi
if [ ${build_visual} = yes ] ; then
  cppflags="${cppflags} -DEXLIB_APP_HAS_TERM -DEXLIB_APP_TERM_INSH"
  use_Getline=yes
fi

# lua :
cppfiles="${cppfiles} ${exlib_home}/exlib/slua/inlib_swig_lua.cpp"

# Python :
if [ "${use_Python}" = "yes" ] ; then
  cppfiles="${cppfiles} ${exlib_home}/exlib/spy/inlib_swig_py.cpp"
fi

if [ ${build_wasm}  = yes ] ; then
  cppflags="${cppflags} -Wno-exceptions" # for SOPHYA to quiet ~ThSafeOp warning.
  use_hdf5=no
  use_Python=no
else    
  use_hdf5=yes
fi

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

use_zip=yes
use_csz=yes
use_cfitsio=yes
use_wcslib=yes
use_lua=yes

. ${bush_home}/use/Getline
. ${bush_home}/use/csz
. ${bush_home}/use/cfitsio
. ${bush_home}/use/hdf5
. ${bush_home}/use/wcslib

. ${bush_home}/use/zip
. ${bush_home}/use/lua

. ${bush_home}/app_trailer_use

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
/bin/cp ${exlib_home}/exlib/spy/inlib.py ../comres/.
#/bin/cp ${exlib_home}/exlib/spy/inlib.py ../Android/res/raw/inlib_py.py

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ${bush_home}/app_trailer
