#!/bin/sh -f

bush_home=`pwd`/../../bush

save_dir=`pwd`

exlib_home="${save_dir}/../../inexlib/exlib"
ourex_home="${save_dir}/../../inexlib/ourex"

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
${bush_home}/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..

from=../ioda/res
if [ ! -d ${from} ] ; then
  echo "directory ${from} not found"
  exit
fi

files=""
files="${files} arialbd.ttf helveticabd.ttf courbd.ttf lucidagrandebd.ttf" #gui fonts.
files="${files} helvetica.ttf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} files.jpg"
files="${files} application_exit.jpg"
files="${files} connect_to_wall.jpg"
files="${files} edit_clear.jpg edit_undo.jpg"
files="${files} move2red.jpg flip_flop.jpg"
files="${files} object_rotate_left.jpg stop_object_rotate_left.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"

files="${files} syncmap.fits"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/TouchSky.style
/bin/cp ${from}/ioda.wall ./comres/TouchSky.wall

#/bin/cp ./icons/scope_128.jpg ./comres/scope.jpg
#/bin/cp ./icons/plot_128.jpg ./comres/plot.jpg
#/bin/cp ./icons/beos_menu.jpg ./comres/.

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////

files=""
files="${files} white.jpg"
files="${files} icon.jpg favicon.ico star_trek_enterprise.bsg"
files="${files} M51.fits ra90dec45.fits"
files="${files} TouchSky.srv"

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
/bin/cp ${exlib_home}/exlib/spy/inlib.py ../comres/.
/bin/rm -R -f ../comres/lib
/bin/cp -R ${ourex_home}/Python/lib ../comres/.

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res

#/////////////////////////////////////////////////////////////
#/// iOS : ///////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

if [ -d ../icons ] ; then
  to=../Cocoa/TouchSky.iconset
  if [ -d ${to} ] ; then
    cp ../icons/icon_16.png ${to}/.
    cp ../icons/icon_32.png ${to}/.
    cp ../icons/icon_128.png ${to}/.
    cp ../icons/icon_256.png ${to}/.
    cp ../icons/icon_512.png ${to}/.
    cp ../icons/icon_32.png ${to}/icon_16@2x.png
    cp ../icons/icon_64.png ${to}/icon_32@2x.png
    cp ../icons/icon_256.png ${to}/icon_128@2x.png
    cp ../icons/icon_512.png ${to}/icon_256@2x.png
    cp ../icons/icon_1024.png ${to}/icon_512@2x.png
    cd ../Cocoa
    iconutil -c icns TouchSky.iconset
    cd ${save_dir}
  fi
  cp ../icons/icon.jpg ../res/.
  cp ../icons/icon.jpg ../comres/.
  cp ../icons/favicon.ico ../res/.
  cp ../icons/favicon.ico ../comres/.
fi

