#!/bin/sh -f

bush_home=`pwd`/../../bush

save_dir=`pwd`

exlib_home="${save_dir}/../../inexlib/exlib"
ourex_home="${save_dir}/../../inexlib/ourex"

${bush_home}/find_rm ../comres '*.*'

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ../../ioda/mgr/cp_std

files="${files} syncmap.fits"
files="${files} m51.fits"
files="${files} python_2_7_lib_py.zip"

for file in ${files} ; do
  /bin/cp ../../ioda/res/${file} ../comres/.
done

/bin/cp ../../ioda/res/ioda.style ../comres/TouchSky.style

#/////////////////////////////////////////////////////////////
#/// from inlib : ////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ../../inexlib/inlib/mgr/cp_insh

for file in ${files} ; do
  /bin/cp ../../inexlib/inlib/inlib/insh/scripts/${file} ../comres/.
done

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////

files=""
files="${files} white.jpg"
files="${files} icon.jpg favicon.ico star_trek_enterprise.bsg"
files="${files} ra90dec45.fits"
files="${files} TouchSky.srv"
files="${files} dc2_rdz_csv.gz"

files="${files} startup.insh"
files="${files} about.insh"
files="${files} web_get_stsci.insh"
files="${files} some_stsci.insh"
files="${files} gui_stsci_simbad.insh"
files="${files} gui_stsci_simbad_ok.insh"
files="${files} gui_pimgs.insh"
files="${files} gui_main.insh"

files="${files} exa_sophya_histo.insh"

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
/bin/cp ${exlib_home}/exlib/spy/inlib.py ../comres/.

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res

#/////////////////////////////////////////////////////////////
#/// iOS : ///////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

if [ -d ../icons ] ; then
  to=../Cocoa/TouchSky.iconset
  if [ -d ${to} ] ; then
    cp ../icons/icon_16.png ${to}/.
    cp ../icons/icon_32.png ${to}/.
    cp ../icons/icon_128.png ${to}/.
    cp ../icons/icon_256.png ${to}/.
    cp ../icons/icon_512.png ${to}/.
    cp ../icons/icon_32.png ${to}/icon_16@2x.png
    cp ../icons/icon_64.png ${to}/icon_32@2x.png
    cp ../icons/icon_256.png ${to}/icon_128@2x.png
    cp ../icons/icon_512.png ${to}/icon_256@2x.png
    cp ../icons/icon_1024.png ${to}/icon_512@2x.png
    cd ../Cocoa
    iconutil -c icns TouchSky.iconset
    cd ${save_dir}
  fi
  cp ../icons/icon.jpg ../res/.
  cp ../icons/icon.jpg ../comres/.
  cp ../icons/favicon.ico ../res/.
  cp ../icons/favicon.ico ../comres/.
fi

